const categories = [
    { 
        slug: 'animais',
        title: 'Animais',
        items: [
            {
                title: 'Bode',
                name: 'bode',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/bode.png'),
            },
            {
                title: 'Boi',
                name: 'boi',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/boi.png'),
            },
            {
                title: 'Borboleta',
                name: 'borboleta',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/borboleta.png'),
            },
            {
                title: 'Cachorro',
                name: 'cachorro',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/cachorro.png'),
            },
            {
                title: 'Cavalo',
                name: 'cavalo',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/cavalo.png'),
            },
            {
                title: 'Cobra',
                name: 'cobra',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/cobra.png'),
            },
            {
                title: 'Galinha',
                name: 'galinha',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/galinha.png'),
            },
            {
                title: 'Gato',
                name: 'gato',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/gato.png'),
            },
            {
                title: 'Golfinho',
                name: 'golfinho',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/golfinho.png'),
            },
            {
                title: 'Joaninha',
                name: 'joaninha',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/joaninha.png'),
            },
            {
                title: 'Peixe',
                name: 'peixe',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/peixe.png'),
            },
            {
                title: 'Polvo',
                name: 'polvo',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/polvo.png'),
            },
            {
                title: 'Rato',
                name: 'rato',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/rato.png'),
            },
            {
                title: 'Vaca',
                name: 'vaca',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/animais/vaca.png'),
            },
        ]
    },
    { 
        slug: 'objetos',
        title: 'Objetos',
        items: [
            {
                title: 'Apito',
                name: 'apito',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/objetos/apito.png'),
            },
            {
                title: 'Arco',
                name: 'arco',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/objetos/arco.png'),
            },
            {
                title: 'Bandeira Quadrada',
                name: 'bandeira-quadrada',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/objetos/bandeira-quadrada.png'),
            },
            {
                title: 'Bandeira Triangular',
                name: 'bandeira-triangular',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/objetos/bandeira-triangular.png'),
            },
            {
                title: 'Borracha',
                name: 'borracha',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/objetos/borracha.png'),
            },
        ]
    },
    { 
        slug: 'pessoas',
        title: 'Pessoas',
        items: [
            {
                title: 'Bandeirinha com raiva',
                name: 'bandeirinha-com-raiva',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/pessoas/bandeirinha-com-raiva.png'),
            },
            {
                title: 'Banhista com boia',
                name: 'banhista-com-boia',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/pessoas/banhista-com-boia.png'),
            },
            {
                title: 'cantor',
                name: 'Cantor',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/pessoas/cantor.png'),
            },
            {
                title: 'Homem de óculos sorrindo',
                name: 'homem-de-oculos-sorrindo',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/pessoas/homem-de-oculos-sorrindo.png'),
            },
            {
                title: 'Robo uma mão levantada',
                name: 'robo-uma-mao-levantada',
                type: 'image',
                image: null,
                x: 24,
                y: 24,
                rotation: 0,
                draggable: true,
                _src: require('@/assets/images/gibi/pessoas/robo-uma-mao-levantada.png'),
            },
        ]
    },
    {
        slug: 'cenarios',
        title: 'Cenários',
        items: [
            {
                title: 'Cenário 1',
                type: 'background',
                _src: require('@/assets/images/gibi/cenarios/luz-cenario-1.png'),
            },                
            {
                title: 'Cenário 2',
                type: 'background',
                _src: require('@/assets/images/gibi/cenarios/luz-cenario-2.png'),
            },                
            {
                title: 'Cenário 3',
                type: 'background',
                _src: require('@/assets/images/gibi/cenarios/luz-cenario-3.png'),
            },                
            {
                title: 'Cenário 4',
                type: 'background',
                _src: require('@/assets/images/gibi/cenarios/luz-cenario-4.png'),
            },                
            {
                title: 'Cenário 5',
                type: 'background',
                _src: require('@/assets/images/gibi/cenarios/luz-cenario-5.png'),
            },                
        ]
    },
    {
        slug: 'baloes',
        title: 'Balões',
        items: [
            {
                title: 'Balão 01',
                name: 'balloon-1',
                type: 'image',
                variant: 'balloon',
                text: 'Insira seu texto aqui',
                image: null,
                _src: require('@/assets/images/gibi/baloes/01.png'),
                width: 125,
                height: 100,
                draggable: true,
                fontSize: 14,
                padding: 8,
            }
        ]
    }
]

export default categories
