version: "3.7"

services:
  app:
    image: registry.seduc.ce.gov.br/luzdosaber-ufc/luz-do-saber-portal:staging
    environment:
      - TZ=America/Fortaleza
      - CI_ENV=staging     
    logging:
      driver: loki
      options:
        loki-url: "http://logsexternos.seduc.ce.gov.br:3100/loki/api/v1/push"
        labels: "luzufc-app-portal"
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.frontend.rule=Host:appluzdosaberdesv.seduc.ce.gov.br        
        - traefik.port=80
        - traefik.docker.network=net_app
        - traefik.frontend.redirect.entryPoint=https
    networks:
      - net_app

networks:
  net_app:
    external: true